book_project/accounts/urls.py
from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

book_project/book_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # product pages
    path('', views.product_list, name='product_list'), #R
    path('product/list/', views.product_list, name='product_list'), # delete future
    path('product/new/', views.product_new, name='product_new'),
    path('product/new-from-url/', views.product_new_from_url, name='product_new_from_url'),
    path('product/edit/<int:pk>', views.product_edit, name='product_edit'),

    # account pages
    path('account/list/', views.account_list, name='account_list'),
    path('account/new/', views.account_new, name='account_new'),
    path('account/edit/<int:pk>', views.account_edit, name='account_edit'),
]

book_project/book_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import book_app.views as book_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_project/book_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Shops():
    # 店舗の定数
    NONE = 0
    BOOTH = 10
    DLSITE = 20
    FANZA_COMIC = 30
    FANZA_DOUJIN = 31
    MELONBOOKS = 40
    TORANOANA = 50

    # 店舗の定数
    SHOPS = (
        (NONE, "なし"),
        (BOOTH, "BOOTH"),
        (DLSITE, "DLSite"),
        (FANZA_COMIC, "FANZA電子書籍"),
        (FANZA_DOUJIN, "FANZA同人"),
        (MELONBOOKS, "メロンブックス"),
    )

    # 自身の情報
    @staticmethod
    def getStopString(shop_num):
        for shops in Shops.SHOPS:
            if shops[0] == shop_num:
                return shops[1]


# 買ったもの
class Product(models.Model):

    # 所有者
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    # 書名
    title = models.CharField(max_length=256, null=True)
    # 著者
    author = models.CharField(max_length=256, null=True)
    # サークル名
    circle = models.CharField(max_length=256, null=True)
    # 購入店舗
    shop = models.IntegerField(choices=Shops.SHOPS, null=True)
    # URL
    url = models.URLField(max_length=512, null=True)
    # 購入日時
    bought_date = models.DateTimeField(null=True, blank=True)
    # 追加日時
    added_date = models.DateTimeField(default=timezone.now)
    # 画像のパス
    image_path = models.ImageField(upload_to='uploads/', blank=True)

    # 自身の情報
    def __str__(self):
        return self.owner.__str__() + ': ' + self.title.__str__()


# 店舗情報
class Account(models.Model):

    # 所有者
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # サイト
    shop = models.IntegerField(choices=Shops.SHOPS)

    # ユーザー名
    user = models.CharField(max_length=256)
    # パスワード
    password = models.CharField(max_length=256)

    # 最終取得日時
    date = models.DateTimeField(null=True, blank=True)

    # 自身の情報
    def __str__(self):
        for shops in Shops.SHOPS:
            if shops[0] == self.shop:
                return self.owner.__str__() + ': ' + shops[1]

book_project/book_app/forms.py
from django import forms
from .models import Product, Account, Shops


class ProductForm(forms.Form):
    shop = forms.ChoiceField(
        label = 'サイト',
        widget=forms.Select,
        choices=Shops.SHOPS,
        required=True,
    )

    url = forms.URLField(
        label='URL',
        max_length=512,
        required=False,
    )

    title = forms.CharField(
        label='書名',
        max_length=256,
        required=True,
    )

    author = forms.CharField(
        label='著者',
        max_length=256,
        required=False,
    )

    circle = forms.CharField(
        label='サークル名',
        max_length=256,
        required=False,
    )

    bought_date = forms.DateField(
        label='購入日',
        required=False,
    )

    image_path=forms.ImageField(
        label='ファイルを選択',
        required=False,
    )

    class Meta:
        model = Product
    #     fields = ('title', 'author', 'circle' 'shop', 'url', 'date', 'image_path')


class AccountForm(forms.Form):
    shop = forms.ChoiceField(
        label = 'サイト',
        widget=forms.Select,
        choices=Shops.SHOPS,
        required=True,
    )

    user = forms.CharField(
        label='ユーザー名',
        max_length=200,
        required=True,
    )

    password = forms.CharField(
        label='パスワード',
        widget = forms.PasswordInput(),
        max_length=200,
        required=True,
    )

book_project/book_app/views.py
from concurrent import futures

from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Product, Account
from .forms import ProductForm, AccountForm

from engine.webscraper import DoujinShop


# global variable
_executor = futures.ThreadPoolExecutor(max_workers=4)


@login_required
def product_list(request):
    products = Product.objects.filter(owner=request.user).order_by('-id')

    # POSTの場合更新処理
    if request.method == "POST":
        # POSTリクエストからpkを取り出す
        pk_id = request.POST.get('pk', None)

        # 指定のpkからproductを取り出す
        product = get_object_or_404(Product, pk=pk_id)

        # 並列処理で商品情報を取得する
        # DoujinShop.UpdateProductInfo(product, False)
        _executor.submit(fn=DoujinShop.UpdateProductInfo, product=product, set_shop_num=False)

        # 同じページにリダイレクトしてPOSTの要求をクリアする
        return redirect('/')

    # render() shortcut eliminates HttpResponce and loader
    return render(request, 'book_app/product_list.html', {'products': products})


@login_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)

        if 'delete' in request.POST:
            return redirect('/')

        if form.is_valid():
            cd = form.cleaned_data

            if 'image_delete' in request.POST:
                image_path = None
            else:
                image_path = cd['image_path']

            Product.objects.create(
                owner=request.user,
                shop = cd['shop'],
                url = cd['url'],
                title = cd['title'],
                author = cd['author'],
                circle = cd['circle'],
                image_path = image_path,
                added_date = timezone.now(),
            )

            return redirect('/')
    else:
        form = ProductForm()
    return render(request, 'book_app/product_new.html', {'form': form})


@login_required
def product_new_from_url(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        # if form.is_valid(): #skip check
        print(form) # if remove this, cause broke
        cd = form.cleaned_data

        _executor.submit(fn=DoujinShop.CreateFromUrl, url=cd['url'], request_by=request.user, set_shop_num=False)

        return redirect('/product/new-from-url/')
    else:
        form = ProductForm()
    return render(request, 'book_app/product_new_from_url.html', {'form': form})


@login_required
def product_edit(request, pk):
    procuct_object = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)

        if 'delete' in request.POST:
            procuct_object.delete()
            return redirect('/')

        if 'image_delete' in request.POST:
            procuct_object.image_path = None

        if form.is_valid():
            cd = form.cleaned_data

            procuct_object.shop = cd['shop']
            procuct_object.url = cd['url']
            procuct_object.title = cd['title']
            procuct_object.author = cd['author']
            procuct_object.circle = cd['circle']
            if cd['image_path'] != None:
                procuct_object.image_path = cd['image_path']

            procuct_object.save()
            return redirect('/')
    else:
        procuct_object = get_object_or_404(Product, pk=pk)

        form = ProductForm({
            'shop': procuct_object.shop,
            'url': procuct_object.url,
            'title': procuct_object.title,
            'author': procuct_object.author,
            'circle': procuct_object.circle,
            'image_path': procuct_object.image_path,
            })

    return render(request, 'book_app/product_new.html', {'form': form})


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user).order_by('-id')
    if request.method == "POST":
        # POSTリクエストからpkを取り出す
        pk_id = request.POST.get('pk',None)

        # 指定のpkからobjを取り出す
        account = Account.objects.get(pk=pk_id)

        # Webスクレイピングを実行
        # DoujinShop.GetProductList(account, request.user)
        _executor.submit(fn=DoujinShop.GetProductList, account=account, request_by=request.user)

        # 同じページにリダイレクトしてPOSTの要求をクリアする
        return redirect('/account/list/')

    return render(request, 'book_app/account_list.html', {'accounts': accounts})


@login_required
def account_new(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        
        if form.is_valid() and form.cleaned_data['shop'] != '0':
            cd = form.cleaned_data
            # アカウントを作って保存
            Account.objects.create(
                owner = request.user,
                shop = cd['shop'],
                user = cd['user'],
                password = cd['password'],
            )

            return redirect('/account/list/')
    else:
        form = AccountForm()
    return render(request, 'book_app/account_new.html', {'form': form})


@login_required
def account_edit(request, pk):
    account_object = get_object_or_404(Account, pk=pk)

    if request.method == "POST":
        form = AccountForm(request.POST)
        
        if form.is_valid() and form.cleaned_data['shop'] != '0':
            cd = form.cleaned_data
            print(cd['shop'])

            account_object.shop = cd['shop']
            account_object.user = cd['user']
            account_object.password = cd['password']

            account_object.save()
            return redirect('/account/list/')
    else:
        form = AccountForm({
            'shop': account_object.shop,
            'user': account_object.user,
            'password': account_object.password,
            })

    return render(request, 'book_app/account_new.html', {'form': form})

book_project/book_app/templates/book_app/account_list.html
{% extends 'book_app/base.html' %}
{% load static %}

<!-- title block -->
{% block title %} - Account List{% endblock %}

<!-- Custom styles for this page -->
{% block pagecss %}
<link href="{% static 'bootstrap/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page level plugins -->
{% block pageplugin %}
<script src="{% static 'bootstrap/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function () {
    $('#dataTable').DataTable();
  });
</script>
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h2 class="h2 mb-2 text-gray-800">アカウントの一覧</h2>
  <p class="mb-4">現在自動取得はDLSite, FANZA同人, FANZA電子書籍, メロンブックスのみです。取得にはとても時間がかかります。</p>

  <!-- functions -->
  <a class="btn btn-primary" href="{% url 'account_new' %}">追加</a>

  <!-- DataTales Example -->
  <div class="card shadow my-3">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">アカウント一覧</h6>
    </div>
    <div class="card-body">

      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        </tableclass>
        <thead>
          <tr>
            <th>店舗</th>
            <th>最終取得日時</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for accounts in accounts %}
          <tr>
            <td><a href="{% url 'account_edit' accounts.pk %}">{{accounts.get_shop_display}}</a></td>
            <td>{{accounts.date}}</td>
            <td>
              <form method="POST">{% csrf_token %}
                <input type="hidden" name="pk" value="{{accounts.pk}}">
                {% if accounts.shop == 20 or accounts.shop == 30 or accounts.shop == 31 or accounts.shop == 40 %}
                <button type="submit" class="btn btn-primary">取得</button>
                {% else %}
                <button type="button" class="btn btn-primary" disabled>取得</button>
                {% endif %}
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

book_project/book_app/templates/book_app/account_new.html
{% extends 'book_app/base.html' %}

<!-- title block -->
{% block title %} - Account New{% endblock %}

<!-- Custom styles for this page -->
{% block pagecss %}
{% endblock %}

<!-- Page level plugins -->
{% block pageplugin %}
{% endblock %}


{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <h2>連携アカウント追加</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>

</div>
<!-- /.container-fluid -->
{% endblock %}

book_project/book_app/templates/book_app/base.html
<!DOCTYPE html>
<html lang='ja'>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <!-- title -->
    <title>Arekke{% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'bootstrap/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this page -->
    {% block pagecss %}
    {% endblock %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Title -->
                    <h1 class="h1 mr-auto">
                        <a href="/">Arekke</a>
                    </h1>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">こんにちは {{ user.username }} さん</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="/product/list/">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    購入した商品一覧
                                </a>
                                <a class="dropdown-item" href="/account/list/">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    連携アカウント
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/accounts/logout/">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    ログアウト
                                </a>
                            </div>
                        </li>
                        {% else %}

                        <li class="nav-item no-arrow">
                            <a class="dropdown-item" href="{% url 'login' %}" class="login">ログイン</a>
                        </li>
                        {% endif %}


                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                {% block content %}
                {% endblock %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ihatomorio 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'bootstrap/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    {% block pageplugin %}
    {% endblock %}


</body>

</html>

book_project/book_app/templates/book_app/product_list.html
{% extends 'book_app/base.html' %}
{% load static %}

<!-- title block -->
{% block title %} - Product List{% endblock %}

<!-- Custom styles for this page -->
{% block pagecss %}
<link href="{% static 'bootstrap/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page level plugins -->
{% block pageplugin %}
<script src="{% static 'bootstrap/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function () {
    var table = $('#dataTable').DataTable({
      // define default order
      "order": [[5, "desc"]],
      // DOM positioning
      "dom": '<"row" <"col"l><"col"p><"col"f> > rt <"row" <"col"l><"col"p><"col text-right"i> >'
    });

    // do on click
    $('#dataTable').on('click', 'td', function () {
      var row_number = table.column(this).index();
      // just author or circle column
      if (row_number == 2 || row_number == 3) {
        // get data where you clicked
        var data = table.cell(this).data();
        // just neither None nor blank(undefined)
        if (data != 'None' && data != undefined) {
          // input to serach query form and redraw
          table.search(data).draw();
        }
      }
    });
  });
</script>
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid mt-3 mb-3">

  <!-- Page Heading -->
  <div class="row">
    <div class="mr-auto">
      <h2 class="h2 mb-2 text-gray-800">購入済み商品の一覧</h2>
      <p class="mb-4">著者またはサークル名をクリックするとその内容で検索されます。</p>
    </div>
  </div>

  <div class="row mt-2 mb-2">
    <!-- functions -->
    <div class="col-auto">
      <a class="btn btn-primary" href="{% url 'product_new' %}">追加</a>
    </div>

    <div class="col-auto">
      <a class="btn btn-secondary" href="{% url 'product_new_from_url' %}">URLから連続追加</a>
    </div>
  </div>


  <!-- DataTales Example -->

  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    </tableclass>
    <thead>
      <tr>
        <th width="120px">表紙</th>
        <th width="20%">題名</th>
        <th width="20%">著者</th>
        <th width="20%">サークル名</th>
        <th>購入日</th>
        <th>追加日</th>
        <th>商品情報</th>
      </tr>
    </thead>
    <tbody>
      {% for products in products %}
      <tr>
        <td>
          {% if products.image_path %}
          {% if products.url %}<a href="{{products.url}}" target="_blank" rel="noopener noreferrer">{% endif %}
            <img src="{{ MEDIA_URL }}{{ products.image_path }}" height="100"></img>
            {% if products.url %}</a>{% endif %}
          {% endif %}
        </td>
        <td>
          <!-- start  spinner -->
          {% if products.title == 'loading' %}
          <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          {% endif %}
          <!-- end  spinner -->

          <!-- start  product name -->
          {% if products.url %}
            <a href="{{products.url}}" target="_blank" rel="noopener noreferrer">{{products.title}}</a>
          {% else %}
            {{ products.title }}
          {% endif %}
          {% if products.shop %}<br><span class="badge badge-primary">{{products.get_shop_display}}</span>{% endif %}
          <!-- end  product name -->
        </td>
        <td>{{products.author}}</td>
        <td>{{products.circle}}</td>
        <td>{{products.bought_date}}</td>
        <td><a href="{% url 'product_edit' products.pk %}">{{products.added_date | date:"Y/m/d H:i:s"}}</a></td>
        <td>{% if products.url %}
          <form method="POST">{% csrf_token %}
            <input type="hidden" name="pk" value="{{products.pk}}">
            <button type="submit" class="btn btn-primary">更新</button>
          </form>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


</div>
<!-- /.container-fluid -->
{% endblock %}

book_project/book_app/templates/book_app/product_new.html
{% extends 'book_app/base.html' %}
{% load widget_tweaks %}

<!-- title block -->
{% block title %} - Product New{% endblock %}

<!-- Custom styles for this page -->
{% block pagecss %}
{% endblock %}

<!-- Page level plugins -->
{% block pageplugin %}
{% endblock %}


{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <h2>本を追加</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-auto">
                {{ form.shop.label_tag }}
                {{ form.shop | add_class:"form-control" }}
            </div>
            <div class="form-group col">
                {{ form.url.label_tag }}
                {{ form.url | add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title | add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.author.label_tag }}
            {{ form.author | add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.circle.label_tag }}
            {{ form.circle | add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.date.label_tag }}
            {{ form.date | add_class:"form-control" }}
        </div>
        <div class="form-group custom-file my-4">
            <label class="custom-file-label" for="customFile">表紙ファイルを選択</label>
            {{ form.image_path | add_class:"custom-file-input" }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">保存</button>
            <button type="submit" class="btn btn-warning" name="image_delete">表紙ファイルを削除して保存</button>
            <button type="submit" class="btn btn-danger" name="delete">この本を削除</button>
        </div>
    </form>

</div>
<!-- /.container-fluid -->
{% endblock %}

book_project/book_app/templates/book_app/product_new_from_url.html
{% extends 'book_app/base.html' %}
{% load widget_tweaks %}

<!-- title block -->
{% block title %} - Product New from URL{% endblock %}

<!-- Custom styles for this page -->
{% block pagecss %}
{% endblock %}

<!-- Page level plugins -->
{% block pageplugin %}
{% endblock %}


{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <h2>本をURLから追加</h2>
    <p class="mb-4">追加してもリスト画面に自動遷移しません。
        <br>この画面では重複するURLは追加しません。
    </p>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group col">
            {{ form.url.label_tag }}
            {{ form.url | add_class:"form-control" }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">追加</button>
        </div>
    </form>

</div>
<!-- /.container-fluid -->
{% endblock %}